# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Rappi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rappi

  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'PMAlertController'
  pod 'NVActivityIndicatorView'
  pod 'AZDropdownMenu'
  pod 'TransitionAnimation', '~>3.0.4'

end
